### ISSUE TITLE
Interface 'azure' does not exist in layer.yaml, should this be azure-integration? 

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-azure#4]
Hi, 

When attempting to build, I get the following error on Juju 2.4.0:

> calvinh@calvinh-ws:~/Source/customers/h-and-m/azure-charm/charm-azure$ charm build
> build: Composing into /home/calvinh/Source/customers/h-and-m/azure-charm/charm-azure
> build: Destination charm directory: /home/calvinh/Source/customers/h-and-m/azure-charm/charm-azure/builds/azure
> build: Unable to locate interface:azure. Do you need to set INTERFACE_PATH?

Looks like the interface name is wrong in layers, so I change it to azure-integration, close azure-integration and set the LAYERS_PATH and then hit this issue:  [https://github.com/juju-solutions/interface-azure-integration/issues/3](https://github.com/juju-solutions/interface-azure-integration/issues/3)

Regards

**Comment by tvansteenburgh** [comment]
This charm isn't finished yet. No need to file bugs until is. You'll know it's finished when it's published to the charm store.
